# Generated by Django 3.0.7 on 2020-06-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BBC',
            new_name='CNet',
        ),
    ]
