# Generated by Django 3.0.7 on 2020-06-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200619_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnet',
            name='href',
            field=models.CharField(max_length=999),
        ),
    ]
