# Generated by Django 3.0.7 on 2020-06-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200619_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
