# Generated by Django 3.0.7 on 2020-06-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corona',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
