# Generated by Django 3.0.7 on 2020-06-28 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid_19', '0002_auto_20200625_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='corona',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
